### ISSUE TITLE
PHP error when using news_categories

### ISSUE THREAD

**Issue by patric-eberle** [exploreimpact/contao-i18nl10n#43]
ich brauche für mein Projekt die Erweiterung news_categories, die wiederum verwendet den widget_tree_picker. Wenn ich nun eine News anlege und die Kategorie ausgewählt habe, wird im Backend dieser Fehler ausgegeben:

Warning: in_array() expects parameter 2 to be array, null given in D:\xampp\htdocs\contaobuch\system\modules\core\lib rary\Contao\System.php on line 110
#0 [internal function]: __error(2, 'in_array() expe...', 'D:\xampp\htdocs...', 110, Array)
#1 D:\xampp\htdocs\contaobuch\system\modules\core\lib rary\Contao\System.php(110): in_array('getInstance', NULL)
#2 D:\xampp\htdocs\contaobuch\system\modules\core\cla sses\Ajax.php(432): Contao\System->import('tl_page_i18nl10...')
#3 D:\xampp\htdocs\contaobuch\system\modules\core\cla sses\Ajax.php(416): Contao\Ajax->executePostActionsHook(Object(Contao\DC_Table))
#4 D:\xampp\htdocs\contaobuch\system\modules\core\cla sses\Backend.php(264): Contao\Ajax->executePostActions(Object(Contao\DC_Table))
#5 D:\xampp\htdocs\contaobuch\contao\main.php(142): Contao\Backend->getBackendModule('news')
#6 D:\xampp\htdocs\contaobuch\contao\main.php(293): Main->run()
#7 {main}

Fatal error: Class 'tl_page_i18nl10n' not found in D:\xampp\htdocs\contaobuch\system\modules\core\lib rary\Contao\System.php on line 110

Ich verwende Contao 3.2.16 und i18nl10n 1.0.3

**Comment by patric-eberle** [comment]
The tl_page_i18nl10n dca is not loaded in this case. Need to move the ajax request to I18nl10nHooks.
