### ISSUE TITLE
tl_content_l10n::appendLanguageInput() called with wrong argument

### ISSUE THREAD

**Issue by rolandschuetz** [exploreimpact/contao-i18nl10n#98]
Does anyone has an idea why this error ocured?

```
PHP Recoverable error: Argument 1 passed to tl_content_l10n::appendLanguageInput() must be an instance of Contao\DataContainer, instance of tl_content given, called in /var/www/clients/client9472/web891/web/system/modules/core/dca/tl_content.php on line 1747 and defined in /var/www/clients/client9472/web891/web/system/modules/i18nl10n/dca/tl_content.php on line 105
#0 /var/www/clients/client9472/web891/web/system/modules/i18nl10n/dca/tl_content.php(105): __error(4096, 'Argument 1 pass...', '/var/www/client...', 105, Array)
#1 /var/www/clients/client9472/web891/web/system/modules/core/dca/tl_content.php(1747): tl_content_l10n->appendLanguageInput(Object(tl_content))
#2 /var/www/clients/client9472/web891/web/system/modules/core/dca/tl_content.php(1705): tl_content->toggleVisibility('564', false, NULL)
#3 /var/www/clients/client9472/web891/web/system/modules/ce-access/CeAccess.php(148): tl_content->toggleIcon(Array, NULL, 'Sichtbarkeit \xC3\xA4...', 'Die Sichtbarkei...', 'visible.gif', ' class="toggle"...')
#4 [internal function]: CeAccess->toggleButton(Array, NULL, 'Sichtbarkeit \xC3\xA4...', 'Die Sichtbarkei...', 'visible.gif', ' class="toggle"...', 'tl_content', NULL, NULL, false, NULL, '690', Object(Contao\DC_Table))
#5 /var/www/clients/client9472/web891/web/system/modules/i18nl10n/dca/tl_content.php(264): call_user_func_array(Array, Array)
#6 /var/www/clients/client9472/web891/web/system/modules/i18nl10n/dca/tl_content.php(207): tl_content_l10n->createVendorListButton(Array, Array)
#7 [internal function]: tl_content_l10n->createButton('toggle', Array, Array)
#8 /var/www/clients/client9472/web891/web/system/modules/i18nl10n/classes/I18nl10nHook.php(553): call_user_func_array(Array, Array)
#9 /var/www/clients/client9472/web891/web/system/modules/core/classes/DataContainer.php(677): Verstaerker\I18nl10n\Classes\I18nl10nHook->Verstaerker\I18nl10n\Classes\{closure}(Array, NULL, 'Sichtbarkeit \xC3\xA4...', 'Die Sichtbarkei...', 'visible.gif', ' class="toggle"...', 'tl_content', NULL, NULL, false, NULL, '690', Object(Contao\DC_Table))
#10 /var/www/clients/client9472/web891/web/system/modules/core/drivers/DC_Table.php(4253): Contao\DataContainer->generateButtons(Array, 'tl_content', NULL, false, NULL, NULL, '690')
#11 /var/www/clients/client9472/web891/web/system/modules/core/drivers/DC_Table.php(378): Contao\DC_Table->parentView()
#12 /var/www/clients/client9472/web891/web/system/modules/core/classes/Backend.php(650): Contao\DC_Table->showAll()
#13 /var/www/clients/client9472/web891/web/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('article')
#14 /var/www/clients/client9472/web891/web/contao/main.php(20): Contao\BackendMain->run()
#15 {main}
```

**Comment by internetinnovations** [comment]
Low priority, needs to be reproduced and tested.
